### ISSUE TITLE
Android O permission denied for window type 2006

### ISSUE THREAD

**Issue by Mateeen** [kevalpatel2106/android-hidden-camera#16] opened 2017-06-19 17:21 UTC
`06-19 22:18:06.485 27339-27339/com.example.mateen.gcmtesting E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.example.mateen.gcmtesting, PID: 27339
                                                                               java.lang.RuntimeException: Unable to start service com.example.mateen.gcmtesting.ActionServices.CameraService@edc3f43 with Intent { cmp=com.example.mateen.gcmtesting/.ActionServices.CameraService (has extras) }: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@8da1cf2 -- permission denied for window type 2006
                                                                                   at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
                                                                                   at android.app.ActivityThread.-wrap20(Unknown Source:0)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@8da1cf2 -- permission denied for window type 2006
                                                                                   at android.view.ViewRootImpl.setView(ViewRootImpl.java:788)
                                                                                   at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                                                                                   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
                                                                                   at com.androidhiddencamera.HiddenCameraService.addPreView(HiddenCameraService.java:125)
                                                                                   at com.androidhiddencamera.HiddenCameraService.startCamera(HiddenCameraService.java:82)
                                                                                   at com.example.mateen.gcmtesting.ActionServices.CameraService.onStartCommand(CameraService.java:100)
                                                                                   at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
                                                                                   at android.app.ActivityThread.-wrap20(Unknown Source:0) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

this error comes when i call the service to take the picture in android O

**Comment by Mateeen** [comment] 2017-06-22 09:24
i have found the solution there need to change only one Flag which android O deprecated you may can appreciate me later :P 
change your flag Windomanger flag "TYPE_SYSTEM_OVERLAY" to "TYPE_APPLICATION_OVERLAY"
please make these changes in your project to make compatible with upcoming android O

**Comment by kevalpatel2106** [comment] 2017-06-22 16:05
@Mateeen Thank you. I will change this and update this in upcoming release.

**Comment by kevalpatel2106** [comment] 2017-11-14 04:11
This issue is fixed in [8fc5634993bd58e8eafd49a386798ec959ed4bfc](https://github.com/kevalpatel2106/android-hidden-camera/commit/8fc5634993bd58e8eafd49a386798ec959ed4bfc).

**Closed by kevalpatel2106** 2017-11-14 04:11 UTC

**Comment by Anurag-Taksykraft** [comment] 2018-04-06 13:58
your Awesome @Mateeen

**Comment by akxhay** [comment] 2018-04-08 10:25
@Mateeen Thanks

**Comment by aaryan1** [comment] 2018-12-12 11:33
Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@88fb2d0 -- permission denied for window type 2010

i m getting this error in android o  please write me solution .

**Comment by SonicCodes** [comment] 2020-02-24 10:54
The Error comes because android blocked this type of overlay for system apps only for security purposes after Android O. You can consider using TYPE_APPLICATION_OVERLAY, which the window appears under crucial System Overlays (Status bar,Menu, ...)

**Comment by bingo125** [comment] 2022-09-15 02:28
> The Error comes because android blocked this type of overlay for system apps only for security purposes after Android O. You can consider using TYPE_APPLICATION_OVERLAY, which the window appears under crucial System Overlays (Status bar,Menu, ...)

thx
